// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-WTaoAXJ7uFEZ6N1H_K-I3aD4dQvPufU',
    appId: '1:645443397615:web:10856b5c41a68fbf89f81a',
    messagingSenderId: '645443397615',
    projectId: 'snakpixel-779f6',
    authDomain: 'snakpixel-779f6.firebaseapp.com',
    storageBucket: 'snakpixel-779f6.appspot.com',
    measurementId: 'G-540RE176Q6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt-T4ltD1Nc25cJ5Z5dVBCUMt34NWxTcE',
    appId: '1:645443397615:android:22b306f9c57d5a6289f81a',
    messagingSenderId: '645443397615',
    projectId: 'snakpixel-779f6',
    storageBucket: 'snakpixel-779f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3vkuREronMPJFIuCH_yTwfT1jg6_iGaQ',
    appId: '1:645443397615:ios:bec8c4c17b34ee7189f81a',
    messagingSenderId: '645443397615',
    projectId: 'snakpixel-779f6',
    storageBucket: 'snakpixel-779f6.appspot.com',
    iosBundleId: 'com.example.snakpix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3vkuREronMPJFIuCH_yTwfT1jg6_iGaQ',
    appId: '1:645443397615:ios:bec8c4c17b34ee7189f81a',
    messagingSenderId: '645443397615',
    projectId: 'snakpixel-779f6',
    storageBucket: 'snakpixel-779f6.appspot.com',
    iosBundleId: 'com.example.snakpix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-WTaoAXJ7uFEZ6N1H_K-I3aD4dQvPufU',
    appId: '1:645443397615:web:0381697a6b97ea8689f81a',
    messagingSenderId: '645443397615',
    projectId: 'snakpixel-779f6',
    authDomain: 'snakpixel-779f6.firebaseapp.com',
    storageBucket: 'snakpixel-779f6.appspot.com',
    measurementId: 'G-9F4NY172XF',
  );
}
